// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://zxsppvvtdplsgafkuukq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4c3BwdnZ0ZHBsc2dhZmt1dWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzNTI0MjEsImV4cCI6MjA0NzkyODQyMX0.n5qEGkfQyAxInTv0_F1w5fVppG8n_NO9RreB5GxCwjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);